# Generated by Django 5.2.8 on 2025-11-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donationhistory_donation_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationhistory',
            name='donation_request',
        ),
        migrations.RemoveField(
            model_name='donationrequest',
            name='completed_at',
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
